/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head';
import React from 'react';
import react, { useState, useEffect } from 'react';
import { Header } from '@/components/shared/Header';

interface Props {
  children?: JSX.Element | JSX.Element[] | string;
  title: string;
}
// Website layout basic components
export const Layout: React.FC<Props> = ({ children, title }) => {
  return (
    <React.Fragment>
      {/* SEO */}
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Web site header component */}
      <Header />

      {/* page content */}
      {children}
    </React.Fragment>
  );
};
